# Generated by Django 4.2.2 on 2023-06-08 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('other', 'Other'), ('meat', 'Meat'), ('fruit', 'Fruit'), ('veggie', 'Veggie'), ('dry', 'Dry Seasoning/Powders'), ('wet', 'Liquids/Oils'), ('sauce', 'Sauce'), ('dairy', 'Dairy'), ('grain', 'Rice/Pasta'), ('product', 'Off-the-Shelf')], max_length=100)),
            ],
        ),
    ]
